### PR TITLE
Switch to the DRM VC4 V3D driver

### PR DESCRIPTION
**Pull request by fhunleth**
Raspbian uses the DRM VC4 V3d driver by default now for the Raspberry Pi
4 so it seems more promising to use it now.

This requires that we turn off rpi-userland since rpi-userland also
supplies OpenGL drivers. This is unfortunate since rpi-userland also
supplies useful camera and video encode libraries and programs.
Buildroot will need to be updated to support both.

### CODE REVIEW

**Comment by fhunleth** [comment]
I think that I'm getting close to getting video working on the RPi4, but I timed out for today.

I've made more changes than this, but I think these are the good ones. There appears to be a missing dependency between Mesa3D and Qt, though, since I could swear that sometimes Qt's EGL plugin isn't being built. (It should auto-detect `EGLFS_DEVICE_INTEGRATION = eglfs_kms` in the qt5base configuration.)

**Comment by fhunleth** [comment]
One more thing, my system boots, the DRM and V3D drivers show prints in `dmesg`:

```
[    8.894643] [drm] Initialized v3d 1.0.0 20180419 for fec00000.v3d on minor 0
[    8.950309] vc4-drm soc:gpu: bound fe600000.firmwarekms (ops vc4_fkms_ops [vc4])
[    8.958632] [drm] Initialized vc4 0.0.0 20140616 for soc:gpu on minor 1
[    8.965535] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[    8.972419] [drm] No driver support for vblank timestamp query.
[    8.978494] [drm] Setting vblank_disable_immediate to false because get_vblank_timestamp == NULL
[    9.119962] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    9.130298] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Feb 27 2018 03:15:32 version 7.45.154 (r684107 CY) FWID 01-4fbe0b04
[    9.191086] Console: switching to colour frame buffer device 240x67
[    9.243741] vc4-drm soc:gpu: fb0: DRM emulated frame buffer device
```

The screen goes blank when webengine_kiosk loads. If you press F5, you can see messages in the log from it reloading, so it thinks that it's drawing to the screen.

I see this error in RingLogger:

```
21:00:50.791 [warn]  webengine_kiosk(stderr): Draw call returned Invalid argument.  Expect corruption.
```

I believe it is due to this:

```
Setting framebuffer size is only available with DRM atomic API
```

I haven't looked into what that means yet.

**Comment by bjufre** [comment]
@fhunleth

I was trying to port scenic driver for rpi4, and I came across this project that uses drm and drm atomic (there’s a file called like that :) ). Hope it can help you more than it did me! 

https://github.com/robclark/kmscube/blob/master/drm-atomic.c

**Comment by fhunleth** [comment]
@bjufre Thanks for that link. I don't think that atomic is a big deal any more. The documentation here was helpful: https://doc.qt.io/qt-5/embedded-linux.html.

Today's progress:

1. I hadn't noticed this, but the mouse cursor is working. It was working yesterday. I think this is a good sign.
2. I turned on Qt's logging to see if anything interesting popped up. This is done by adding `{'QT_LOGGING_RULES', 'qt.qpa.*=true'}` to the environment.
3. `/dev/dri/card1` was being used. I didn't know if it made a difference so I forced it to `/dev/dri/card0` in a config file and set `QT_QPA_EGLFS_KMS_CONFIG`. In `webengine_kiosk`, this looked like:

```
    File.write(
      "/tmp/kms.conf",
      """
      {
        "device": "/dev/dri/card0",
        "outputs": [
          { "name": "HDMI1", "mode": "1920x1080" }
        ]
      }
      """
    )

    port =
      Port.open({:spawn_executable, cmd}, [
        {:args, cmd_args},
        {:cd, priv_dir},
        {:packet, 2},
        :use_stdio,
        :binary,
        :exit_status,
        {:env,
         [{'QT_LOGGING_RULES', 'qt.qpa.*=true'}, {'QT_QPA_EGLFS_KMS_CONFIG', '/tmp/kms.conf'}]}
      ])
```

That didn't work.

**Comment by fhunleth** [comment]
Today's progress:

1. Fixed a `udev` warning about `kvm`. I also pulled in new group above it for dri, but that didn't change anything.
2. Enabled v3d support in mesa3d. Buildroot doesn't support enabling it, but Raspbian uses it. This didn't fix anything.
3. Instrumented mesa3d and the Linux kernel to get more info on the `Draw call returned Invalid argument.  Expect corruption.` print. This is due to a failed `ioctl`. I'm convinced whatever is causing this is the core problem. I don't know yet. It doesn't seem like the `ioctl` is being routed to the vc4 drm drivers...

**Comment by fhunleth** [comment]
Ugh - timed out.

This function isn't getting called. https://github.com/raspberrypi/linux/blob/e2d2941326922b63d722ebc46520c3a2287b675f/drivers/gpu/drm/vc4/vc4_v3d.c#L314

Both the vc4 and v3d kernel modules are loaded and the device tree overlay is there. There must be some step that we're missing to bind the two together....

**Comment by fhunleth** [comment]
Today's progress:

Verified more that the vc4 isn't being "bound" to v3d. I don't see anything on Raspbian.

mesa3d is version 19.0.8 and Raspbian is running 19.2.0. There are v3d updates in 19.1.x, but I didn't see anything in 19.2.0. I tried to update, but found out that 19.1.0 is a pretty big change (the build system changed!). Buildroot `master` has the fixes, but I'll need to pull in the patches. Upgrading does not seem likely to me to fix it, but it does have a long list of updates for v3d...

**Comment by fhunleth** [comment]
Got busy, but didn't forget. I posted to the Raspberry Pi forum. Fingers crossed.

https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=254293

**Comment by fhunleth** [comment]
This may be more involved. I have updates for mesa3d 19.2.1 (luckily, that's just backporting a patch set from Buildroot). The problem is that there are two "video cards". Qt needs to be configured to use one video card (card1) for setting screen resolution and the other video card (card0) for drawing. I'm not sure how to configure the Qt eglfs_kms plugin to do this.

**Comment by fhunleth** [comment]
Another question posted to https://forum.qt.io/topic/107764/drm-kms-configuration-for-raspberry-pi-4.

**Comment by miks** [comment]
@fhunleth do you have any plans/time on this?
Problems I encountered:
1) without DRM VC4 V3D driver webengine is simply not playing any videos (neither mp4/webmp). It's  reporting DEMUXER_ERROR_COULD_NOT_OPEN error 
2) with DRM VC4 V3D webegine just hangs on loading

Can you, please, check that your kiosk_system_rpi4 is playing any kind of video? Maybe it's just my local build problems.

**Comment by fhunleth** [comment]
This is on the backburner for me. I'm not too optimistic about getting time to work on it, since it seems like the current commercial backers of kiosk work are doing fine with RPi 3's and not looking to switch to RPi 4's. (to my knowledge)

I'm not sure I got as far as you, though. I got to the point where web pages were being loaded, but not rendered. Also, webengine wasn't hanging or at least I don't think it was since the mouse cursor would change shapes depending on whether I was over a text entry field or not.

**Comment by miks** [comment]
I'm sorry for off-topic, but are there any video playback involved with RPI 3's kiosks involved?
If so, how it's performance-wise?
I tried to compile rpi3-kiosk, but it failed as older erlang/elixir is required.

**Comment by fhunleth** [comment]
Le Tote maintains https://github.com/LeToteTeam/kiosk_system_rpi3. I thought that they had video playing back, but I don't know for sure. I'm pretty sure that their version of Erlang is pretty recent. They might be able to help some too.

I'm not sure if you're doing this for a commercial project, but if so, I'd suggest contacting a contract dev firm to help make this happen faster. DM me on the Elixir-lang Slack and I can try making suggestions. If this isn't commercial, then I think that the route to success is to get things working on Raspbian and then switch over to Nerves in the future when RPi 4 issues are resolved.

**Comment by miks** [comment]
Thanks, if I will get any progress regarding VC4 I will post it here.

**Comment by fhunleth** [comment]
Update: The updated version of mesa3d is available now in Buildroot 2019.11. See https://github.com/nerves-project/nerves_system_br/pull/392. This version has very important updates to mesa3d for using the VC4 driver (technically the RPi4 has a VC6, but the Linux driver has the same name as the other RPi's).

**Comment by fhunleth** [comment]
Still not there, but I'm pretty sure this will be needed: https://github.com/nerves-project/nerves_system_br/pull/397

**Comment by miks** [comment]
`BR2_PACKAGE_MESA3D_OSMESA` has been renamed to `BR2_PACKAGE_MESA3D_OSMESA_CLASSIC` in buildroot 2019.11

**Comment by fhunleth** [comment]
@miks Thanks - I pushed an updated configuration with that change and to enable the V3D driver. That's where I left off last year.

**Comment by miks** [comment]
I just built against `kvm` branch, but there is no /dev/drm/* devices on my rpi4.

drm module has been loaded:
```
[    4.927955] media: Linux media interface: v0.10
[    4.947112] videodev: Linux video capture interface: v2.00
[    5.112895] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[    5.126704] bcm2835_codec: module is from the staging directory, the quality is unknown, you have been warned.
[    5.140738] bcm2835-codec bcm2835-codec: Device registered as /dev/video10
[    5.147912] bcm2835-codec bcm2835-codec: Loaded V4L2 decode
[    5.155534] bcm2835-codec bcm2835-codec: Device registered as /dev/video11
[    5.162696] bcm2835-codec bcm2835-codec: Loaded V4L2 encode
[    5.170647] bcm2835-codec bcm2835-codec: Device registered as /dev/video12
[    5.177789] bcm2835-codec bcm2835-codec: Loaded V4L2 isp
[    6.788812] bcm2835_v4l2: module is from the staging directory, the quality is unknown, you have been warned.
[    9.878826] f2fs_msg: 6 callbacks suppressed
[    9.878834] F2FS-fs (mmcblk0p3): Found nat_bits in checkpoint
[    9.931973] F2FS-fs (mmcblk0p3): Mounted with checkpoint version = 232add1b
[    9.982402] [drm] No displays found. Consider forcing hotplug if HDMI is attached
[    9.990220] vc4-drm soc:gpu: bound fe600000.firmwarekms (ops vc4_fkms_ops [vc4])
[    9.998269] [drm] Initialized vc4 0.0.0 20140616 for soc:gpu on minor 0
[   10.005164] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[   10.011984] [drm] No driver support for vblank timestamp query.
[   10.018123] [drm] Setting vblank_disable_immediate to false because get_vblank_timestamp == NULL
```

Is it possible that something is broken after last commits?

**Comment by fhunleth** [comment]
Sorry - my `nerves_defconfig` is using an option that's in `nerves_system_br` `master` and not in the current release. We're due for a `nerves_system_br` release, so let me get that out.

Also, I haven't had any time to do anything with the Raspberry Pi 4 since December so it could be possible that something is more broken than it was then, but I don't think that it could be much more broken.

**Comment by fhunleth** [comment]
I bumped the version of `nerves_system_br`. I have not tested this, but I believe it to be closer to what I was actually testing late last year since it includes the V3D patch to mesa3d.

**Pull request closed without merging**
